export const cardList = [
  {
    id: '1',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '2',
    caption: 'TextCaption',
    imageUrl:
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
    taggedImages: [
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
      'https://images.freeimages.com/images/large-previews/2fe/butterfly-1390152.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '3',
    caption: 'TextCaption',
    imageUrl:
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
    taggedImages: [
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
      'https://images.pexels.com/photos/326055/pexels-photo-326055.jpeg?cs=srgb&dl=light-landscape-nature-326055.jpg&fm=jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '4',
    caption: 'TextCaption',
    imageUrl: 'https://www.w3schools.com/howto/img_forest.jpg',
    taggedImages: [
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '5',
    caption: 'TextCaption',
    imageUrl: 'https://www.w3schools.com/howto/img_forest.jpg',
    taggedImages: [
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
      'https://www.w3schools.com/howto/img_forest.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '6',
    caption: 'TextCaption',
    imageUrl:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
    taggedImages: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHnvmYdYBV34WwNaWawDc6FsS-MZLM8elBz9RDYp6AnvBwqf-hFA',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '7',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '8',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '9',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '10',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '11',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '12',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '13',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
  {
    id: '14',
    caption: 'TextCaption',
    imageUrl:
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    taggedImages: [
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
      'https://wallpaperbrowse.com/media/images/3848765-wallpaper-images-download.jpg',
    ],
    vendorData: {
      vendor: '<vendor>',
      location: 'Bangalore',
      price: '200$',
      name: 'Color Dunes LLC',
    },
    taggedTexts: [
      {
        year: '2019',
        season: 'Spring',
        category: 'Accessories',
        gender: 'Women',
      },
      {
        year: '2019',
        season: 'Fall',
        category: 'Accessories',
        gender: 'Women',
      },
    ],
  },
];
